language: python
python: 3.7.3
dist: xenial
sudo: true

cache: pip

branches:
  only: master

install:
    - pip install -r ./requirements.txt

script:
    - git clean -f -d -x
    - git config --global user.name "Travis CI"
    - git config --global user.email "travis@travis-ci.com"
    - git remote add gh-token "https://${GH_TOKEN}@github.com/umd-lhcb/ut-hw-doc.git"
    - git fetch gh-token && git fetch gh-token gh-pages:gh-pages

after_success:
    - mkdocs gh-deploy -v --clean --remote-name gh-token
env:
    global:
        secure: "no3U0HdGm5yGZdGt/otVFmfdXCiJy+QE0y+p6XWGFgumMqPI5oli2slACeCW2iT0POj2GVr9DcNZctg8ihEDDgB25fro8HsToXr43f4EhXU4v5wRa2AWlEEwXwSRVuUHlry8xds/C6ImMwEl+RvvuAtg5azvLSqr1KGcybkszeHWgzwZpmG0r2QmpumUb9nBBH+P5ZYXTJ5r8LIaJ3rDrNUVCikBl6Frwv05U+XkINufMDp42Karg6yq+EiIolVhzf5bhqH8q7Nuf366rsKChskLE8dXocLSVgh43qfOaykTyeroKJdQXP+dRs+MjRsEOFvgxj6RRguqPRsYxHsrrWtszVeHStHWhWKDM08RJvpZPXWm1czuLrDi/O2Kms4Ik/EKsxhjqz6xSmBn3+go1PC7D2tCzVj9aGQGpvM16c3JvvtNI+LEatpKi/zaXqV/Afm5Dz+DDl3rwIcf/AlASY7qzvwXa+nrNkE6EjHgYlCOk7PAmLPnKaPpReEOJwnMR/Ck6ETVC4n0zzCzn916mZnHVuRoA2pC0+Zx2D1PB4FIwgOADWR2k+j2kv/MhKT+0JY7eTYXbPTjWMYaT9TM/nzkJTGA+p05SGjey2dmQLOlR2J4RwEaWBEP/yBBQdQxLiCl2bxxo2G52EV26HWCXByt1LDLS7g0xS8iBocMNLo="
