language: python
python: 3.8

cache: pip

branches:
    only: master

install:
    - pip install -r ./requirements.txt

script:
    - mkdocs build

env:
    global:
        secure: "0GQiF4BDArbpJKOqXum8HS+D9Z4sR+HW7Mzl9uXDxpFVX5GJB5/0fmDkNs3R9PDq2ElReudL7XmTZ770VZKCO2jYpo1ZGDN19CaaYP1DB1Ei/4PlIIdeddOQ+/4biCYdEg5zZE3pdkkxfoDIk1fCkyLzsn/XbHfrnZ19fzg+yh0JGbxEVoYZcJBIluVydIW8M5p6tCf6utLxGkPDA9W8tWc4d9jo6JMc+TcjwbHl9Ho5Oc8AmCsPun0inVbEB32fcZKcEcv8dP6nbDURL7RULs3y19y+0fcZIJpSy1mR4tOBJtBTwjiu+7MyOF0zEb5RTMeUBkIjB6IJtUFCc0TreG889xyuaTbB6fUvQsOEua2qTZfAYI19lqlWXdmHgbSlKqia9Iubb3jjBGzhy8DsSbOts032O7xGW2Yjmx6dl7jnEFVQof3YMeUS20GHx7xQwgfiyKToOSThwuv5Hp8DZz1RQB8c8Kut+ChDyBYoZZLcZ1C1NLJW+rJhi9zeqZNY5GnbyKnIjfrc7nfr4+zkN0NRATGhU7h4V8tKqS5fwLihzFa3v/h6BatGF5+li9cK3ZcHty36bgCuceTbDb0jKTLRpC5F3Oe9Mftwp4gbpavr1ykiOxvGGWWi2yuwYDSXQVa9yPpEecNnq2TbcU/qRpk9C7uStY5bzjaCaXmmEd0="

deploy:
    provider: pages
    skip_cleanup: true
    keep_history: true
    github_token: $GH_TOKEN
    on:
        branch: master
    target_branch: gh-pages
    local_dir: site
