language: python
python: 3.7.3
dist: xenial
sudo: true

cache: pip

branches:
  only: master

install:
    - pip install -r ./requirements.txt

script:
    - git clean -f -d -x
    - git config --global user.name "Travis CI"
    - git config --global user.email "travis@travis-ci.com"
    - git remote add gh-token "https://${GH_TOKEN}@github.com/umd-lhcb/ut-hw-doc.git"
    - git fetch gh-token && git fetch gh-token gh-pages:gh-pages

after_success:
    - mkdocs gh-deploy -v --clean --remote-name gh-token
env:
    global:
        secure: LOrhmot9sQ5rEh/Qhfm7pj6jC/gtIkNZipIdPk2bCkAL8d2mMqtiDjCXUxb/6OdTVVJyjFEPKG2+z02PBkhU6qtOTKOhpKAEPUEgmOmL05IxFRte8ME6sr8OpR+q8n22Lu6CiWnZa4cjxH08+Y6QlkcdG123hajyk/GQgO88ouplsZyJo9E4mptLGhnJkYKb11lk1VxZAcWfGxhTGkU8YFpgt3lpAURkO288/cfIhH6tKzLVmvqo9dG3criZQ1vgbnUgBehK8ht3cQMIEj5aJY/T0hq/eWle+VpCw19DY7y0zdLuFgqIGb3VFaqjx9Y6oqdu/cRCJvUvFwVxhc3aRULJg/pEAoPzaWmkXVNPj704M7+0c1VeT7gwADKacTsRNzYTeMFCZge06trURn0nRXXhnBXm9pQbvIAX3wubWrzIn/QHlGf4FV1R+Yv9kmz9X6Fh/96utJ+L5TPlna53tio+Y93Zn4JzdRV9c4tCgqIZPWT5xXg7/ocReQwaV+NsZwQLI+InfQTRSd9a1cYOohXZoYRdS9FZ4J6uyrjrfwmz0gXYzGnq3wwnNmUXGwASSLwSeJ4WevaYoGOEVBJe0ooE2DKO2HAzaqCh7JSXNt4nCyOQuvn6m/6sjOtn73852GNlLWEUkuIZoFJk4wILRyNdebgt0lhbqPppH0JlC5Q=
