site_name: 'UMD UT hardware documentation'
site_url: https://umd-lhcb.github.io/ut-hw-doc

repo_name: umd-lhcb/ut-hw-doc
repo_url: https://github.com/umd-lhcb/ut-hw-doc

theme:
    name: 'material'
    logo: umd_logo.png
    include_search_page: false
    search_index_only: true
    feature:
        - instant
    palette:
        scheme: default
        primary: red
        accent: indigo

markdown_extensions:
    - admonition
    - pymdownx.critic
    - pymdownx.caret
    - attr_list
    - footnotes

plugins:
    - search
    - minify:
        minify_html: true

nav:
    - Home:
        - Getting started: index.md
        - license.md
        - Boxes: burnin/box_algorithm.md
    - Backplane:
        Backplane depopution: backplane/backplane_depop.md
    - DCB:
        - DCB mechanical assembly: dcb/dcb_assembly/dcb_assembly.md
        - DCB QA: dcb/dcb_qa/dcb_qa.md
        - DCB Shipping: dcb/dcb_shipping/dcb_shipping.md
        - Use production DCB with Pathfinder: dcb/dcb_prod_with_pathfinder/dcb_prod_with_pathfinder.md
    - LVR:
        - LVR mechanical assembly: lvr/lvr_assembly/lvr_assembly.md
        - LVR Setup/Initial QA: lvr/lvr_qa/lvr_qa.md
        - LVR Final QA: lvr/qa_final/qa_final.md
        - LVR Configuration: lvr/lvr_config/lvr_config.md
        - CCM Identification Guide: lvr/ccm_id/ccm_id.md
        - CCM Test Stand Configuration: lvr/ccm_test_stand_config/ccm_test_stand_config.md
        - CCM QA: lvr/ccm_qa/ccm_qa.md
        - LVR shipping: lvr/lvr_shipping/lvr_shipping.md
    - MiniDAQ:
        - MiniDAQ usage: minidaq/minidaq_usage.md
        - CentOS tips: minidaq/centos_tips.md
    - Burn-in:
        - Burn-in hardware setup: burnin/burnin_hw_setup/burnin_hw_setup.md
        - Burn-in software setup: burnin/burnin_sw_setup.md
        - LVR burn-in operations: burnin/lvr_operations/lvr_operations.md
        - DCB burn-in operations: burnin/dcb_operations.md
    - Test stand documentation:
        - LVR Monitor Hardware: teststands/rpi-general/lvr-monitor-errata.md
        - LVR Final QA: teststands/lvr-finalqa/finalqa-setup.md
        - CCM QA: teststands/ccm-qa/ccmqa-setup.md
    - CERN:
        - CERN visual inspection: cern/cern_visual_inspection/cern_visual_inspection.md
        - CERN QA: cern/cern_qa/cern_qa.md
        - DCB depopulation: cern/cern_installation/DCB_depopulation.md
