name: "CI"

on:
  pull_request:
  push:
      branches:
          - master

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v13
      with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
              experimental-features = nix-command flakes

    - run: nix develop --no-update-lock-file -c mkdocs build
    - run: ls

    - uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
          branch: gh-pages
          folder: site
